### ISSUE TITLE
jenkins schedule k8s default pod alway failed with 100s timeout

### ISSUE THREAD

**Issue by purelind** [PingCAP-QE/ee-ops#409]
schedule default k8s pod failed with error

```
Error in provisioning; agent=KubernetesSlave name: default-jhfkf, template=PodTemplate{id='bc6c1d4296b4a646c70ffd279fe27173e151c486c69e53ebba909ff2509bb12d', name='default', namespace='jenkins-ci-default', slaveConnectTimeout=100, label='jenkins-jenkins-agent', serviceAccount='default', nodeUsageMode=NORMAL, podRetention='Never', containers=[ContainerTemplate{name='jnlp', image='jenkins/inbound-agent:4.11-1', workingDir='/home/jenkins/agent', command='sleep', args='', resourceRequestCpu='512m', resourceRequestMemory='512Mi', resourceRequestEphemeralStorage='', resourceLimitCpu='512m', resourceLimitMemory='512Mi', resourceLimitEphemeralStorage='', envVars=[KeyValueEnvVar [getValue()=http://jenkins.apps.svc.cluster.local:8080/jenkins, getKey()=JENKINS_URL]], livenessProbe=ContainerLivenessProbe{execArgs='', timeoutSeconds=0, initialDelaySeconds=0, failureThreshold=0, periodSeconds=0, successThreshold=0}}]}. Container jnlp. Logs: sleep: missing operand
Try 'sleep --help' for more information.

Error in provisioning; agent=KubernetesSlave name: default-jhfkf, template=PodTemplate{id='bc6c1d4296b4a646c70ffd279fe27173e151c486c69e53ebba909ff2509bb12d', name='default', namespace='jenkins-ci-default', slaveConnectTimeout=100, label='jenkins-jenkins-agent', serviceAccount='default', nodeUsageMode=NORMAL, podRetention='Never', containers=[ContainerTemplate{name='jnlp', image='jenkins/inbound-agent:4.11-1', workingDir='/home/jenkins/agent', command='sleep', args='', resourceRequestCpu='512m', resourceRequestMemory='512Mi', resourceRequestEphemeralStorage='', resourceLimitCpu='512m', resourceLimitMemory='512Mi', resourceLimitEphemeralStorage='', envVars=[KeyValueEnvVar [getValue()=http://jenkins.apps.svc.cluster.local:8080/jenkins, getKey()=JENKINS_URL]], livenessProbe=ContainerLivenessProbe{execArgs='', timeoutSeconds=0, initialDelaySeconds=0, failureThreshold=0, periodSeconds=0, successThreshold=0}}]}
java.lang.IllegalStateException: Pod 'default-jhfkf' is terminated. Status: Failed
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:206)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:48)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:82)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by purelind** [comment]
Due to the misconfigured container `Command to run` parameter defined in the config cloud.
Current false config 
```
Command to run: sleep
```
Correct config should leave this parameter empty
```
Command to run: 
```

**Comment by wuhuizuo** [comment]
Now we have not this problem.
